# Build stage
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force && npm ci

COPY . .

RUN npm run generate
RUN npm run build

FROM node:20-alpine

WORKDIR /app


COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./
COPY .env.example ./.env.example

CMD npm run migrate && npm run start:prod
